# Generated by Django 5.1.1 on 2024-10-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_uploaded', models.BooleanField(default=False)),
                ('uploaded_image_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
