# Generated by Django 5.1.1 on 2024-10-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureextract',
            old_name='ean',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='featureextract',
            old_name='mrp',
            new_name='MRP',
        ),
    ]
