# Generated by Django 5.1.1 on 2024-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0002_rename_ean_featureextract_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureextract',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
