# Generated by Django 5.1.1 on 2024-10-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extractor', '0004_featureextract_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureextract',
            name='image_uploaded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='featureextract',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
